# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        symbolic execution: 3
        fuzzing: 3
        root cause: 2
        root cause analysis: 2
        exploit generation: 1
        SMT solver: 2
        AFL: 1
        vulnerability detection: 1
        software security: 1
        embedded system: 1
# 通知の閾値
score_threshold: 0
