# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        symbolic execution: 3 
        fuzzing: 3 
        root causes: 2 
        SAT solver: 2 
        SMT solver: 2 
        AFL: 1 
        penetration testing: 1 
        Vulnerability Detection: 1 
        Software Security: 1 
        embedded system: 1
